services:
  bff:
    image: rodynaamrfathygouda/smartbackend-api:latest
    container_name: smartbackend-container
    ports:
      - "8003:8000"
    env_file:
      - ./bff.env
    depends_on:
      redis:
        condition: service_healthy
      navigation:
        condition: service_started
      positioning:
        condition: service_started
    restart: unless-stopped

  navigation:
    image: rodynaamrfathygouda/navigation-api:latest
    container_name: navigation-container
    ports:
      - "8000:8000"
    env_file:
      - ./navigation.env
    restart: unless-stopped

  positioning:
    image: rodynaamrfathygouda/positioning-api:latest
    container_name: positioning-container
    ports:
      - "8001:8000"
    env_file:
      - ./positioning.env
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

networks:
  default:
    name: bff-network
